name: Pull Request Labeled

on:
  pull_request:
    types: [labeled]

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
  invalid:
    runs-on: ubuntu-latest
    steps:
      - name: Reply to Pull Request
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            We are happy to see you're contributing to fastjs, but we are unable to merge this pull request for now, because:
            - This pull request does not fix a bug.
            - This pull request need to have some changes.
            - This pull request doesn't have a valid issue.
            - You did not follow our [Contributing Guidelines](https://docs.fastjs.cc/other/contributing.html).
            - This pull request violates our [Code of Conduct](https://docs.fastjs.cc/other/code-of-conduct.html).

      - name: Close Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const label = github.context.payload.label;
            if (label.name === 'Resolution: Invalid') {
              github.rest.pulls.update({
                pull_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'closed'
              });
            }